-- Fix the contactInfo error by replacing it with contactMessages
DROP TABLE IF EXISTS public.contactinfo;

CREATE TABLE IF NOT EXISTS public."contactMessages" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text,
  phone text,
  message text,
  date text,
  status text
);

ALTER PUBLICATION supabase_realtime ADD TABLE public."contactMessages";
