-- Create abbots table
CREATE TABLE IF NOT EXISTS public.abbots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  position text,
  year text,
  image text
);

-- Create news table
CREATE TABLE IF NOT EXISTS public.news (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  date text,
  excerpt text,
  content text,
  category text,
  image text
);

-- Create activities table
CREATE TABLE IF NOT EXISTS public.activities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  type text,
  date text,
  time text,
  image text
);

-- Create gallery table
CREATE TABLE IF NOT EXISTS public.gallery (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  count integer,
  status text,
  category text,
  url text
);

-- Create users table
CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  role text,
  email text,
  password text
);

-- Create donations table
CREATE TABLE IF NOT EXISTS public.donations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  amount numeric,
  date text,
  status text
);

-- Create announcements table
CREATE TABLE IF NOT EXISTS public.announcements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  text text,
  link text,
  status text
);

-- Create popups table
CREATE TABLE IF NOT EXISTS public.popups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text,
  content text,
  image text,
  status text
);

-- Create contactInfo table
CREATE TABLE IF NOT EXISTS public.contactInfo (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text,
  email text,
  phone text,
  message text,
  date text
);

-- Create settings table
CREATE TABLE IF NOT EXISTS public.settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key text,
  value text
);

-- Enable Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE public.abbots;
ALTER PUBLICATION supabase_realtime ADD TABLE public.news;
ALTER PUBLICATION supabase_realtime ADD TABLE public.activities;
ALTER PUBLICATION supabase_realtime ADD TABLE public.gallery;
ALTER PUBLICATION supabase_realtime ADD TABLE public.users;
ALTER PUBLICATION supabase_realtime ADD TABLE public.donations;
ALTER PUBLICATION supabase_realtime ADD TABLE public.announcements;
ALTER PUBLICATION supabase_realtime ADD TABLE public.popups;
ALTER PUBLICATION supabase_realtime ADD TABLE public.contactInfo;
ALTER PUBLICATION supabase_realtime ADD TABLE public.settings;
